// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/rickiekarp/homeserver/ShoppingNote.proto

package net.rickiekarp.homeserver.domain;

public interface ShoppingNoteListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShoppingNoteList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ShoppingNote note = 1;</code>
   */
  java.util.List<net.rickiekarp.homeserver.domain.ShoppingNote> 
      getNoteList();
  /**
   * <code>repeated .ShoppingNote note = 1;</code>
   */
  net.rickiekarp.homeserver.domain.ShoppingNote getNote(int index);
  /**
   * <code>repeated .ShoppingNote note = 1;</code>
   */
  int getNoteCount();
  /**
   * <code>repeated .ShoppingNote note = 1;</code>
   */
  java.util.List<? extends net.rickiekarp.homeserver.domain.ShoppingNoteOrBuilder> 
      getNoteOrBuilderList();
  /**
   * <code>repeated .ShoppingNote note = 1;</code>
   */
  net.rickiekarp.homeserver.domain.ShoppingNoteOrBuilder getNoteOrBuilder(
      int index);
}
