// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/rickiekarp/homeserver/ShoppingStores.proto

package net.rickiekarp.homeserver.domain;

/**
 * Protobuf type {@code ShoppingStoreList}
 */
public  final class ShoppingStoreList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ShoppingStoreList)
    ShoppingStoreListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShoppingStoreList.newBuilder() to construct.
  private ShoppingStoreList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShoppingStoreList() {
    store_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShoppingStoreList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShoppingStoreList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              store_ = new java.util.ArrayList<net.rickiekarp.homeserver.domain.ShoppingStore>();
              mutable_bitField0_ |= 0x00000001;
            }
            store_.add(
                input.readMessage(net.rickiekarp.homeserver.domain.ShoppingStore.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        store_ = java.util.Collections.unmodifiableList(store_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.rickiekarp.homeserver.domain.ShoppingStoreProtos.internal_static_ShoppingStoreList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.rickiekarp.homeserver.domain.ShoppingStoreProtos.internal_static_ShoppingStoreList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.rickiekarp.homeserver.domain.ShoppingStoreList.class, net.rickiekarp.homeserver.domain.ShoppingStoreList.Builder.class);
  }

  public static final int STORE_FIELD_NUMBER = 1;
  private java.util.List<net.rickiekarp.homeserver.domain.ShoppingStore> store_;
  /**
   * <code>repeated .ShoppingStore store = 1;</code>
   */
  public java.util.List<net.rickiekarp.homeserver.domain.ShoppingStore> getStoreList() {
    return store_;
  }
  /**
   * <code>repeated .ShoppingStore store = 1;</code>
   */
  public java.util.List<? extends net.rickiekarp.homeserver.domain.ShoppingStoreOrBuilder> 
      getStoreOrBuilderList() {
    return store_;
  }
  /**
   * <code>repeated .ShoppingStore store = 1;</code>
   */
  public int getStoreCount() {
    return store_.size();
  }
  /**
   * <code>repeated .ShoppingStore store = 1;</code>
   */
  public net.rickiekarp.homeserver.domain.ShoppingStore getStore(int index) {
    return store_.get(index);
  }
  /**
   * <code>repeated .ShoppingStore store = 1;</code>
   */
  public net.rickiekarp.homeserver.domain.ShoppingStoreOrBuilder getStoreOrBuilder(
      int index) {
    return store_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < store_.size(); i++) {
      output.writeMessage(1, store_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < store_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, store_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.rickiekarp.homeserver.domain.ShoppingStoreList)) {
      return super.equals(obj);
    }
    net.rickiekarp.homeserver.domain.ShoppingStoreList other = (net.rickiekarp.homeserver.domain.ShoppingStoreList) obj;

    if (!getStoreList()
        .equals(other.getStoreList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStoreCount() > 0) {
      hash = (37 * hash) + STORE_FIELD_NUMBER;
      hash = (53 * hash) + getStoreList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingStoreList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.rickiekarp.homeserver.domain.ShoppingStoreList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ShoppingStoreList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ShoppingStoreList)
      net.rickiekarp.homeserver.domain.ShoppingStoreListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.rickiekarp.homeserver.domain.ShoppingStoreProtos.internal_static_ShoppingStoreList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.rickiekarp.homeserver.domain.ShoppingStoreProtos.internal_static_ShoppingStoreList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.rickiekarp.homeserver.domain.ShoppingStoreList.class, net.rickiekarp.homeserver.domain.ShoppingStoreList.Builder.class);
    }

    // Construct using net.rickiekarp.homeserver.domain.ShoppingStoreList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStoreFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (storeBuilder_ == null) {
        store_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        storeBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.rickiekarp.homeserver.domain.ShoppingStoreProtos.internal_static_ShoppingStoreList_descriptor;
    }

    @java.lang.Override
    public net.rickiekarp.homeserver.domain.ShoppingStoreList getDefaultInstanceForType() {
      return net.rickiekarp.homeserver.domain.ShoppingStoreList.getDefaultInstance();
    }

    @java.lang.Override
    public net.rickiekarp.homeserver.domain.ShoppingStoreList build() {
      net.rickiekarp.homeserver.domain.ShoppingStoreList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.rickiekarp.homeserver.domain.ShoppingStoreList buildPartial() {
      net.rickiekarp.homeserver.domain.ShoppingStoreList result = new net.rickiekarp.homeserver.domain.ShoppingStoreList(this);
      int from_bitField0_ = bitField0_;
      if (storeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          store_ = java.util.Collections.unmodifiableList(store_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.store_ = store_;
      } else {
        result.store_ = storeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.rickiekarp.homeserver.domain.ShoppingStoreList) {
        return mergeFrom((net.rickiekarp.homeserver.domain.ShoppingStoreList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.rickiekarp.homeserver.domain.ShoppingStoreList other) {
      if (other == net.rickiekarp.homeserver.domain.ShoppingStoreList.getDefaultInstance()) return this;
      if (storeBuilder_ == null) {
        if (!other.store_.isEmpty()) {
          if (store_.isEmpty()) {
            store_ = other.store_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStoreIsMutable();
            store_.addAll(other.store_);
          }
          onChanged();
        }
      } else {
        if (!other.store_.isEmpty()) {
          if (storeBuilder_.isEmpty()) {
            storeBuilder_.dispose();
            storeBuilder_ = null;
            store_ = other.store_;
            bitField0_ = (bitField0_ & ~0x00000001);
            storeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStoreFieldBuilder() : null;
          } else {
            storeBuilder_.addAllMessages(other.store_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.rickiekarp.homeserver.domain.ShoppingStoreList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.rickiekarp.homeserver.domain.ShoppingStoreList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<net.rickiekarp.homeserver.domain.ShoppingStore> store_ =
      java.util.Collections.emptyList();
    private void ensureStoreIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        store_ = new java.util.ArrayList<net.rickiekarp.homeserver.domain.ShoppingStore>(store_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.rickiekarp.homeserver.domain.ShoppingStore, net.rickiekarp.homeserver.domain.ShoppingStore.Builder, net.rickiekarp.homeserver.domain.ShoppingStoreOrBuilder> storeBuilder_;

    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public java.util.List<net.rickiekarp.homeserver.domain.ShoppingStore> getStoreList() {
      if (storeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(store_);
      } else {
        return storeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public int getStoreCount() {
      if (storeBuilder_ == null) {
        return store_.size();
      } else {
        return storeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public net.rickiekarp.homeserver.domain.ShoppingStore getStore(int index) {
      if (storeBuilder_ == null) {
        return store_.get(index);
      } else {
        return storeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder setStore(
        int index, net.rickiekarp.homeserver.domain.ShoppingStore value) {
      if (storeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStoreIsMutable();
        store_.set(index, value);
        onChanged();
      } else {
        storeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder setStore(
        int index, net.rickiekarp.homeserver.domain.ShoppingStore.Builder builderForValue) {
      if (storeBuilder_ == null) {
        ensureStoreIsMutable();
        store_.set(index, builderForValue.build());
        onChanged();
      } else {
        storeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder addStore(net.rickiekarp.homeserver.domain.ShoppingStore value) {
      if (storeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStoreIsMutable();
        store_.add(value);
        onChanged();
      } else {
        storeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder addStore(
        int index, net.rickiekarp.homeserver.domain.ShoppingStore value) {
      if (storeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStoreIsMutable();
        store_.add(index, value);
        onChanged();
      } else {
        storeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder addStore(
        net.rickiekarp.homeserver.domain.ShoppingStore.Builder builderForValue) {
      if (storeBuilder_ == null) {
        ensureStoreIsMutable();
        store_.add(builderForValue.build());
        onChanged();
      } else {
        storeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder addStore(
        int index, net.rickiekarp.homeserver.domain.ShoppingStore.Builder builderForValue) {
      if (storeBuilder_ == null) {
        ensureStoreIsMutable();
        store_.add(index, builderForValue.build());
        onChanged();
      } else {
        storeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder addAllStore(
        java.lang.Iterable<? extends net.rickiekarp.homeserver.domain.ShoppingStore> values) {
      if (storeBuilder_ == null) {
        ensureStoreIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, store_);
        onChanged();
      } else {
        storeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder clearStore() {
      if (storeBuilder_ == null) {
        store_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        storeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public Builder removeStore(int index) {
      if (storeBuilder_ == null) {
        ensureStoreIsMutable();
        store_.remove(index);
        onChanged();
      } else {
        storeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public net.rickiekarp.homeserver.domain.ShoppingStore.Builder getStoreBuilder(
        int index) {
      return getStoreFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public net.rickiekarp.homeserver.domain.ShoppingStoreOrBuilder getStoreOrBuilder(
        int index) {
      if (storeBuilder_ == null) {
        return store_.get(index);  } else {
        return storeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public java.util.List<? extends net.rickiekarp.homeserver.domain.ShoppingStoreOrBuilder> 
         getStoreOrBuilderList() {
      if (storeBuilder_ != null) {
        return storeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(store_);
      }
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public net.rickiekarp.homeserver.domain.ShoppingStore.Builder addStoreBuilder() {
      return getStoreFieldBuilder().addBuilder(
          net.rickiekarp.homeserver.domain.ShoppingStore.getDefaultInstance());
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public net.rickiekarp.homeserver.domain.ShoppingStore.Builder addStoreBuilder(
        int index) {
      return getStoreFieldBuilder().addBuilder(
          index, net.rickiekarp.homeserver.domain.ShoppingStore.getDefaultInstance());
    }
    /**
     * <code>repeated .ShoppingStore store = 1;</code>
     */
    public java.util.List<net.rickiekarp.homeserver.domain.ShoppingStore.Builder> 
         getStoreBuilderList() {
      return getStoreFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        net.rickiekarp.homeserver.domain.ShoppingStore, net.rickiekarp.homeserver.domain.ShoppingStore.Builder, net.rickiekarp.homeserver.domain.ShoppingStoreOrBuilder> 
        getStoreFieldBuilder() {
      if (storeBuilder_ == null) {
        storeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            net.rickiekarp.homeserver.domain.ShoppingStore, net.rickiekarp.homeserver.domain.ShoppingStore.Builder, net.rickiekarp.homeserver.domain.ShoppingStoreOrBuilder>(
                store_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        store_ = null;
      }
      return storeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ShoppingStoreList)
  }

  // @@protoc_insertion_point(class_scope:ShoppingStoreList)
  private static final net.rickiekarp.homeserver.domain.ShoppingStoreList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.rickiekarp.homeserver.domain.ShoppingStoreList();
  }

  public static net.rickiekarp.homeserver.domain.ShoppingStoreList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShoppingStoreList>
      PARSER = new com.google.protobuf.AbstractParser<ShoppingStoreList>() {
    @java.lang.Override
    public ShoppingStoreList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShoppingStoreList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShoppingStoreList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShoppingStoreList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.rickiekarp.homeserver.domain.ShoppingStoreList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

