// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/rickiekarp/homeserver/ShoppingNote.proto

package net.rickiekarp.homeserver.domain;

public interface ShoppingNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ShoppingNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int32 user_id = 4;</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>.google.protobuf.Timestamp dateBought = 5;</code>
   * @return Whether the dateBought field is set.
   */
  boolean hasDateBought();
  /**
   * <code>.google.protobuf.Timestamp dateBought = 5;</code>
   * @return The dateBought.
   */
  com.google.protobuf.Timestamp getDateBought();
  /**
   * <code>.google.protobuf.Timestamp dateBought = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateBoughtOrBuilder();

  /**
   * <code>int32 store_id = 6;</code>
   * @return The storeId.
   */
  int getStoreId();

  /**
   * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
   * @return Whether the dateAdded field is set.
   */
  boolean hasDateAdded();
  /**
   * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
   * @return The dateAdded.
   */
  com.google.protobuf.Timestamp getDateAdded();
  /**
   * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateAddedOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
