// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/rickiekarp/homeserver/ShoppingNote.proto

package net.rickiekarp.homeserver.domain;

/**
 * Protobuf type {@code ShoppingNote}
 */
public  final class ShoppingNote extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ShoppingNote)
    ShoppingNoteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ShoppingNote.newBuilder() to construct.
  private ShoppingNote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ShoppingNote() {
    title_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ShoppingNote();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ShoppingNote(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 25: {

            price_ = input.readDouble();
            break;
          }
          case 32: {

            userId_ = input.readInt32();
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateBought_ != null) {
              subBuilder = dateBought_.toBuilder();
            }
            dateBought_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateBought_);
              dateBought_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            storeId_ = input.readInt32();
            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateAdded_ != null) {
              subBuilder = dateAdded_.toBuilder();
            }
            dateAdded_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateAdded_);
              dateAdded_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastUpdated_ != null) {
              subBuilder = lastUpdated_.toBuilder();
            }
            lastUpdated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastUpdated_);
              lastUpdated_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.rickiekarp.homeserver.domain.ShoppingNoteProtos.internal_static_ShoppingNote_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.rickiekarp.homeserver.domain.ShoppingNoteProtos.internal_static_ShoppingNote_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.rickiekarp.homeserver.domain.ShoppingNote.class, net.rickiekarp.homeserver.domain.ShoppingNote.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  public int getId() {
    return id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private double price_;
  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  public double getPrice() {
    return price_;
  }

  public static final int USER_ID_FIELD_NUMBER = 4;
  private int userId_;
  /**
   * <code>int32 user_id = 4;</code>
   * @return The userId.
   */
  public int getUserId() {
    return userId_;
  }

  public static final int DATEBOUGHT_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp dateBought_;
  /**
   * <code>.google.protobuf.Timestamp dateBought = 5;</code>
   * @return Whether the dateBought field is set.
   */
  public boolean hasDateBought() {
    return dateBought_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dateBought = 5;</code>
   * @return The dateBought.
   */
  public com.google.protobuf.Timestamp getDateBought() {
    return dateBought_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateBought_;
  }
  /**
   * <code>.google.protobuf.Timestamp dateBought = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateBoughtOrBuilder() {
    return getDateBought();
  }

  public static final int STORE_ID_FIELD_NUMBER = 6;
  private int storeId_;
  /**
   * <code>int32 store_id = 6;</code>
   * @return The storeId.
   */
  public int getStoreId() {
    return storeId_;
  }

  public static final int DATEADDED_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp dateAdded_;
  /**
   * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
   * @return Whether the dateAdded field is set.
   */
  public boolean hasDateAdded() {
    return dateAdded_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
   * @return The dateAdded.
   */
  public com.google.protobuf.Timestamp getDateAdded() {
    return dateAdded_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateAdded_;
  }
  /**
   * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateAddedOrBuilder() {
    return getDateAdded();
  }

  public static final int LASTUPDATED_FIELD_NUMBER = 8;
  private com.google.protobuf.Timestamp lastUpdated_;
  /**
   * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
   * @return Whether the lastUpdated field is set.
   */
  public boolean hasLastUpdated() {
    return lastUpdated_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
   * @return The lastUpdated.
   */
  public com.google.protobuf.Timestamp getLastUpdated() {
    return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
  }
  /**
   * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
    return getLastUpdated();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (price_ != 0D) {
      output.writeDouble(3, price_);
    }
    if (userId_ != 0) {
      output.writeInt32(4, userId_);
    }
    if (dateBought_ != null) {
      output.writeMessage(5, getDateBought());
    }
    if (storeId_ != 0) {
      output.writeInt32(6, storeId_);
    }
    if (dateAdded_ != null) {
      output.writeMessage(7, getDateAdded());
    }
    if (lastUpdated_ != null) {
      output.writeMessage(8, getLastUpdated());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (price_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, price_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, userId_);
    }
    if (dateBought_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDateBought());
    }
    if (storeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, storeId_);
    }
    if (dateAdded_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDateAdded());
    }
    if (lastUpdated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getLastUpdated());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.rickiekarp.homeserver.domain.ShoppingNote)) {
      return super.equals(obj);
    }
    net.rickiekarp.homeserver.domain.ShoppingNote other = (net.rickiekarp.homeserver.domain.ShoppingNote) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (java.lang.Double.doubleToLongBits(getPrice())
        != java.lang.Double.doubleToLongBits(
            other.getPrice())) return false;
    if (getUserId()
        != other.getUserId()) return false;
    if (hasDateBought() != other.hasDateBought()) return false;
    if (hasDateBought()) {
      if (!getDateBought()
          .equals(other.getDateBought())) return false;
    }
    if (getStoreId()
        != other.getStoreId()) return false;
    if (hasDateAdded() != other.hasDateAdded()) return false;
    if (hasDateAdded()) {
      if (!getDateAdded()
          .equals(other.getDateAdded())) return false;
    }
    if (hasLastUpdated() != other.hasLastUpdated()) return false;
    if (hasLastUpdated()) {
      if (!getLastUpdated()
          .equals(other.getLastUpdated())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId();
    if (hasDateBought()) {
      hash = (37 * hash) + DATEBOUGHT_FIELD_NUMBER;
      hash = (53 * hash) + getDateBought().hashCode();
    }
    hash = (37 * hash) + STORE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStoreId();
    if (hasDateAdded()) {
      hash = (37 * hash) + DATEADDED_FIELD_NUMBER;
      hash = (53 * hash) + getDateAdded().hashCode();
    }
    if (hasLastUpdated()) {
      hash = (37 * hash) + LASTUPDATED_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdated().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.rickiekarp.homeserver.domain.ShoppingNote parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.rickiekarp.homeserver.domain.ShoppingNote prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ShoppingNote}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ShoppingNote)
      net.rickiekarp.homeserver.domain.ShoppingNoteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.rickiekarp.homeserver.domain.ShoppingNoteProtos.internal_static_ShoppingNote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.rickiekarp.homeserver.domain.ShoppingNoteProtos.internal_static_ShoppingNote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.rickiekarp.homeserver.domain.ShoppingNote.class, net.rickiekarp.homeserver.domain.ShoppingNote.Builder.class);
    }

    // Construct using net.rickiekarp.homeserver.domain.ShoppingNote.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      title_ = "";

      price_ = 0D;

      userId_ = 0;

      if (dateBoughtBuilder_ == null) {
        dateBought_ = null;
      } else {
        dateBought_ = null;
        dateBoughtBuilder_ = null;
      }
      storeId_ = 0;

      if (dateAddedBuilder_ == null) {
        dateAdded_ = null;
      } else {
        dateAdded_ = null;
        dateAddedBuilder_ = null;
      }
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.rickiekarp.homeserver.domain.ShoppingNoteProtos.internal_static_ShoppingNote_descriptor;
    }

    @java.lang.Override
    public net.rickiekarp.homeserver.domain.ShoppingNote getDefaultInstanceForType() {
      return net.rickiekarp.homeserver.domain.ShoppingNote.getDefaultInstance();
    }

    @java.lang.Override
    public net.rickiekarp.homeserver.domain.ShoppingNote build() {
      net.rickiekarp.homeserver.domain.ShoppingNote result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.rickiekarp.homeserver.domain.ShoppingNote buildPartial() {
      net.rickiekarp.homeserver.domain.ShoppingNote result = new net.rickiekarp.homeserver.domain.ShoppingNote(this);
      result.id_ = id_;
      result.title_ = title_;
      result.price_ = price_;
      result.userId_ = userId_;
      if (dateBoughtBuilder_ == null) {
        result.dateBought_ = dateBought_;
      } else {
        result.dateBought_ = dateBoughtBuilder_.build();
      }
      result.storeId_ = storeId_;
      if (dateAddedBuilder_ == null) {
        result.dateAdded_ = dateAdded_;
      } else {
        result.dateAdded_ = dateAddedBuilder_.build();
      }
      if (lastUpdatedBuilder_ == null) {
        result.lastUpdated_ = lastUpdated_;
      } else {
        result.lastUpdated_ = lastUpdatedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.rickiekarp.homeserver.domain.ShoppingNote) {
        return mergeFrom((net.rickiekarp.homeserver.domain.ShoppingNote)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.rickiekarp.homeserver.domain.ShoppingNote other) {
      if (other == net.rickiekarp.homeserver.domain.ShoppingNote.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.getUserId() != 0) {
        setUserId(other.getUserId());
      }
      if (other.hasDateBought()) {
        mergeDateBought(other.getDateBought());
      }
      if (other.getStoreId() != 0) {
        setStoreId(other.getStoreId());
      }
      if (other.hasDateAdded()) {
        mergeDateAdded(other.getDateAdded());
      }
      if (other.hasLastUpdated()) {
        mergeLastUpdated(other.getLastUpdated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.rickiekarp.homeserver.domain.ShoppingNote parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.rickiekarp.homeserver.domain.ShoppingNote) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 3;</code>
     * @return The price.
     */
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 3;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private int userId_ ;
    /**
     * <code>int32 user_id = 4;</code>
     * @return The userId.
     */
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 user_id = 4;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(int value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 user_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dateBought_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBoughtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     * @return Whether the dateBought field is set.
     */
    public boolean hasDateBought() {
      return dateBoughtBuilder_ != null || dateBought_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     * @return The dateBought.
     */
    public com.google.protobuf.Timestamp getDateBought() {
      if (dateBoughtBuilder_ == null) {
        return dateBought_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateBought_;
      } else {
        return dateBoughtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     */
    public Builder setDateBought(com.google.protobuf.Timestamp value) {
      if (dateBoughtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateBought_ = value;
        onChanged();
      } else {
        dateBoughtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     */
    public Builder setDateBought(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateBoughtBuilder_ == null) {
        dateBought_ = builderForValue.build();
        onChanged();
      } else {
        dateBoughtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     */
    public Builder mergeDateBought(com.google.protobuf.Timestamp value) {
      if (dateBoughtBuilder_ == null) {
        if (dateBought_ != null) {
          dateBought_ =
            com.google.protobuf.Timestamp.newBuilder(dateBought_).mergeFrom(value).buildPartial();
        } else {
          dateBought_ = value;
        }
        onChanged();
      } else {
        dateBoughtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     */
    public Builder clearDateBought() {
      if (dateBoughtBuilder_ == null) {
        dateBought_ = null;
        onChanged();
      } else {
        dateBought_ = null;
        dateBoughtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateBoughtBuilder() {
      
      onChanged();
      return getDateBoughtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateBoughtOrBuilder() {
      if (dateBoughtBuilder_ != null) {
        return dateBoughtBuilder_.getMessageOrBuilder();
      } else {
        return dateBought_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateBought_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dateBought = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateBoughtFieldBuilder() {
      if (dateBoughtBuilder_ == null) {
        dateBoughtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateBought(),
                getParentForChildren(),
                isClean());
        dateBought_ = null;
      }
      return dateBoughtBuilder_;
    }

    private int storeId_ ;
    /**
     * <code>int32 store_id = 6;</code>
     * @return The storeId.
     */
    public int getStoreId() {
      return storeId_;
    }
    /**
     * <code>int32 store_id = 6;</code>
     * @param value The storeId to set.
     * @return This builder for chaining.
     */
    public Builder setStoreId(int value) {
      
      storeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 store_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStoreId() {
      
      storeId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dateAdded_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateAddedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     * @return Whether the dateAdded field is set.
     */
    public boolean hasDateAdded() {
      return dateAddedBuilder_ != null || dateAdded_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     * @return The dateAdded.
     */
    public com.google.protobuf.Timestamp getDateAdded() {
      if (dateAddedBuilder_ == null) {
        return dateAdded_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateAdded_;
      } else {
        return dateAddedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     */
    public Builder setDateAdded(com.google.protobuf.Timestamp value) {
      if (dateAddedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateAdded_ = value;
        onChanged();
      } else {
        dateAddedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     */
    public Builder setDateAdded(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateAddedBuilder_ == null) {
        dateAdded_ = builderForValue.build();
        onChanged();
      } else {
        dateAddedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     */
    public Builder mergeDateAdded(com.google.protobuf.Timestamp value) {
      if (dateAddedBuilder_ == null) {
        if (dateAdded_ != null) {
          dateAdded_ =
            com.google.protobuf.Timestamp.newBuilder(dateAdded_).mergeFrom(value).buildPartial();
        } else {
          dateAdded_ = value;
        }
        onChanged();
      } else {
        dateAddedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     */
    public Builder clearDateAdded() {
      if (dateAddedBuilder_ == null) {
        dateAdded_ = null;
        onChanged();
      } else {
        dateAdded_ = null;
        dateAddedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateAddedBuilder() {
      
      onChanged();
      return getDateAddedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateAddedOrBuilder() {
      if (dateAddedBuilder_ != null) {
        return dateAddedBuilder_.getMessageOrBuilder();
      } else {
        return dateAdded_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateAdded_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp dateAdded = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateAddedFieldBuilder() {
      if (dateAddedBuilder_ == null) {
        dateAddedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateAdded(),
                getParentForChildren(),
                isClean());
        dateAdded_ = null;
      }
      return dateAddedBuilder_;
    }

    private com.google.protobuf.Timestamp lastUpdated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     * @return Whether the lastUpdated field is set.
     */
    public boolean hasLastUpdated() {
      return lastUpdatedBuilder_ != null || lastUpdated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     * @return The lastUpdated.
     */
    public com.google.protobuf.Timestamp getLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      } else {
        return lastUpdatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     */
    public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdated_ = value;
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     */
    public Builder setLastUpdated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = builderForValue.build();
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     */
    public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (lastUpdated_ != null) {
          lastUpdated_ =
            com.google.protobuf.Timestamp.newBuilder(lastUpdated_).mergeFrom(value).buildPartial();
        } else {
          lastUpdated_ = value;
        }
        onChanged();
      } else {
        lastUpdatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     */
    public Builder clearLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
        onChanged();
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {
      
      onChanged();
      return getLastUpdatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      if (lastUpdatedBuilder_ != null) {
        return lastUpdatedBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdated = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastUpdatedFieldBuilder() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdated(),
                getParentForChildren(),
                isClean());
        lastUpdated_ = null;
      }
      return lastUpdatedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ShoppingNote)
  }

  // @@protoc_insertion_point(class_scope:ShoppingNote)
  private static final net.rickiekarp.homeserver.domain.ShoppingNote DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.rickiekarp.homeserver.domain.ShoppingNote();
  }

  public static net.rickiekarp.homeserver.domain.ShoppingNote getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ShoppingNote>
      PARSER = new com.google.protobuf.AbstractParser<ShoppingNote>() {
    @java.lang.Override
    public ShoppingNote parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ShoppingNote(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ShoppingNote> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ShoppingNote> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.rickiekarp.homeserver.domain.ShoppingNote getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

