// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/rickiekarp/homeserver/ShoppingNote.proto

package net.rickiekarp.homeserver.domain;

public final class ShoppingNoteProtos {
  private ShoppingNoteProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShoppingNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ShoppingNote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ShoppingNoteList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ShoppingNoteList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,net/rickiekarp/homeserver/ShoppingNote" +
      ".proto\032\037google/protobuf/timestamp.proto\"" +
      "\353\001\n\014ShoppingNote\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 " +
      "\001(\t\022\r\n\005price\030\003 \001(\001\022\017\n\007user_id\030\004 \001(\005\022.\n\nd" +
      "ateBought\030\005 \001(\0132\032.google.protobuf.Timest" +
      "amp\022\020\n\010store_id\030\006 \001(\005\022-\n\tdateAdded\030\007 \001(\013" +
      "2\032.google.protobuf.Timestamp\022/\n\013lastUpda" +
      "ted\030\010 \001(\0132\032.google.protobuf.Timestamp\"/\n" +
      "\020ShoppingNoteList\022\033\n\004note\030\001 \003(\0132\r.Shoppi" +
      "ngNoteB8\n net.rickiekarp.homeserver.doma" +
      "inB\022ShoppingNoteProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ShoppingNote_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ShoppingNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ShoppingNote_descriptor,
        new java.lang.String[] { "Id", "Title", "Price", "UserId", "DateBought", "StoreId", "DateAdded", "LastUpdated", });
    internal_static_ShoppingNoteList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ShoppingNoteList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ShoppingNoteList_descriptor,
        new java.lang.String[] { "Note", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
