CREATE USER 'dev'@'%' IDENTIFIED BY '9c12a9df2394a0b98eh32a0fee0b5067';
GRANT ALL PRIVILEGES ON * . * TO 'dev'@'%';
FLUSH PRIVILEGES;

CREATE USER 'user'@'%' IDENTIFIED BY '1f3BcE47Fa91c4fe7df4';
GRANT ALL PRIVILEGES ON * . * TO 'user'@'%';
FLUSH PRIVILEGES;


CREATE DATABASE assistant_login;
CREATE DATABASE assistant_data;