extra.set("springBootVersion", "2.1.7.RELEASE")
extra.set("flywayVersion", "5.2.4")
extra.set("guavaVersion", "28.0-jre")
extra.set("gsonVersion", "2.8.5")
extra.set("jacksonVersion", "2.9.9")
extra.set("okhttpVersion", "4.0.1")
extra.set("jsonVersion", "20180813")
