DROP DATABASE IF EXISTS videothek;
CREATE DATABASE IF NOT EXISTS videothek;

USE videothek;

CREATE TABLE IF NOT EXISTS Kunde (
KundenID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
KVorname VARCHAR(15),
KNachname VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS Sachgebiet (
SachgebietID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
SachgebietName VARCHAR(15)
);

CREATE TABLE IF NOT EXISTS Video (
VideoNr VARCHAR(15) PRIMARY KEY NOT NULL,
Titel VARCHAR(15),
Gebiet INT(5) NOT NULL,
FOREIGN KEY (Gebiet) REFERENCES Sachgebiet (SachgebietID)
);

CREATE TABLE IF NOT EXISTS Exemplar (
ExemplarNr INT(5),
VideoNr VARCHAR(15),
PRIMARY KEY (ExemplarNr, VideoNr),
FOREIGN KEY (VideoNr) REFERENCES Video (VideoNr)
);

CREATE TABLE IF NOT EXISTS Ausleih (
AusleihNr INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
KundenID INT(5) NOT NULL,
ExemplarNr INT(5) NOT NULL,
LeihStart VARCHAR(15),
LeihEnde VARCHAR(15),
FOREIGN KEY (KundenID) REFERENCES Kunde (KundenID),
FOREIGN KEY (ExemplarNr) REFERENCES Exemplar (ExemplarNr)
);
