// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/rickiekarp/loginserver/WorldProto.proto

package net.rickiekarp.loginserver.domain;

public interface WorldListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorldList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .World world = 1;</code>
   */
  java.util.List<net.rickiekarp.loginserver.domain.World> 
      getWorldList();
  /**
   * <code>repeated .World world = 1;</code>
   */
  net.rickiekarp.loginserver.domain.World getWorld(int index);
  /**
   * <code>repeated .World world = 1;</code>
   */
  int getWorldCount();
  /**
   * <code>repeated .World world = 1;</code>
   */
  java.util.List<? extends net.rickiekarp.loginserver.domain.WorldOrBuilder> 
      getWorldOrBuilderList();
  /**
   * <code>repeated .World world = 1;</code>
   */
  net.rickiekarp.loginserver.domain.WorldOrBuilder getWorldOrBuilder(
      int index);
}
