// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/rickiekarp/loginserver/WorldProto.proto

package net.rickiekarp.loginserver.domain;

public interface WorldProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorldProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string url = 3;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>int32 worldstatusid = 4;</code>
   */
  int getWorldstatusid();
}
